### ISSUE TITLE
Module Name Attribute Build Issue

### ISSUE THREAD

**Issue by RajasekarPR** [davidhayden/Robots.OrchardCore#1]
Hi @davidhayden 

I am getting the below error when adding the Robots.OrchardCore nuget package in my orchard core solution.

Error Message : ModuleNameAttribute is exist in both OrchardCore.Abstraction and OrchardCore.Module.Abstractions.

Kindly do the needful.

**Comment by davidhayden** [comment]
You are running beta 3 of Orchard Core CMS, and this module was still using beta 2.

I upgraded to latest version of beta 3 on Nuget. Errors fixed.
